# Generated by Django 2.1.7 on 2019-07-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['name'], 'verbose_name': 'User group'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='video',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='video',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='video',
            name='max_bearing',
        ),
        migrations.RemoveField(
            model_name='video',
            name='max_power',
        ),
        migrations.RemoveField(
            model_name='video',
            name='model',
        ),
        migrations.RemoveField(
            model_name='video',
            name='music',
        ),
        migrations.RemoveField(
            model_name='video',
            name='nodes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='position',
        ),
        migrations.RemoveField(
            model_name='video',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='video',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='video',
            name='u_location',
        ),
        migrations.RemoveField(
            model_name='video',
            name='u_quantity',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_combine',
        ),
        migrations.AlterField(
            model_name='video',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created'),
        ),
    ]
