# Generated by Django 2.1.7 on 2019-07-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visions', '0002_auto_20190703_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['name'], 'verbose_name': 'Video'},
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, max_length=128, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='video',
            name='show',
            field=models.CharField(blank=True, max_length=128, verbose_name='show'),
        ),
        migrations.AddField(
            model_name='video',
            name='show_time',
            field=models.CharField(blank=True, max_length=128, verbose_name='Show Time'),
        ),
    ]
