# Generated by Django 2.1.7 on 2019-07-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visions', '0003_auto_20190703_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name'], 'verbose_name': 'Material'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='classifys',
        ),
        migrations.AddField(
            model_name='material',
            name='end_time',
            field=models.CharField(default='', max_length=128, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='material',
            name='start_time',
            field=models.CharField(default='', max_length=128, verbose_name='Start time'),
        ),
        migrations.AddField(
            model_name='material',
            name='video_name',
            field=models.CharField(default='', max_length=128, verbose_name='Video name'),
        ),
        migrations.AddField(
            model_name='material',
            name='video_path',
            field=models.CharField(blank=True, max_length=128, verbose_name='Video path'),
        ),
        migrations.AlterField(
            model_name='material',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created'),
        ),
    ]
