# Generated by Django 2.1.7 on 2019-07-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visions', '0004_auto_20190705_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='effect',
            options={'ordering': ['name'], 'verbose_name': 'Effect'},
        ),
        migrations.RemoveField(
            model_name='effect',
            name='explain',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='music',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='video_combines',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='x1',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='x2',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='y1',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='y2',
        ),
        migrations.AddField(
            model_name='effect',
            name='end_time',
            field=models.CharField(default='', max_length=128, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='effect',
            name='method',
            field=models.CharField(blank=True, max_length=128, verbose_name='Method'),
        ),
        migrations.AddField(
            model_name='effect',
            name='start_time',
            field=models.CharField(default='', max_length=128, verbose_name='Start time'),
        ),
        migrations.AddField(
            model_name='effect',
            name='time_duration',
            field=models.CharField(default='', max_length=128, verbose_name='Time duration'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created'),
        ),
    ]
