# Generated by Django 2.1.7 on 2019-08-16 03:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('disease_code', models.CharField(blank=True, max_length=128, verbose_name='Disease code')),
                ('case_number', models.CharField(blank=True, max_length=128, verbose_name='Case Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Case',
                'ordering': ['disease_code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('org_id', 'disease_code')},
        ),
    ]
