# Generated by Django 2.1.7 on 2019-08-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['name'], 'verbose_name': 'Case'},
        ),
        migrations.AddField(
            model_name='case',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('org_id', 'name')},
        ),
    ]
